# Basic configuration
baseurl: https://atsign.dev/
canonifyURLs: true
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
languageCode: en
paginate: 7
rssLimit: 10

defaultContentLanguage: en

# Sitemap Config
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
# TODO

# Relative Permalinks
# permalinks:
#   blog: /blog/:title/

build:
  writeStats: true

minify:
  tdewolff:
    html:
      keepWhitespace: false
