main:
  - name: Docs
    url: /docs/
    weight: 1

  - name: Showcase
    url: /showcase/
    weight: 2

  - name: Community
    url: /community/
    weight: 3

  - name: IoT
    url: https://iot.atsign.dev/
    weight: 4
