name: DeployStaging
on:
  push:
    branches:
      - trunk

env:
  DEV_URL: 'dev3.atsign.wtf'
  IOT_URL: 'iot3.atsign.wtf'

jobs:
  deploy:
    if: ${{ github.repository == 'atsign-foundation/atsign.dev-3.0' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Staging
        run: npm run build:staging

      - name: Deploy Staging
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ${{ env.DEV_URL }}

      - name: Build IoT Staging
        run: npm run build:staging:iot

      - name: Deploy IoT Staging
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          external_repository: atsign-foundation/iot.atsign.dev
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ${{ env.IOT_URL }}
